### ISSUE TITLE
Can't flip dakimakura on hand by the version of 1.12.2

### ISSUE THREAD

**Issue by HawkEye1015** [RiskyKen/DakimakuraMod#3]
I can flip dakimakura on hand by the version of 1.7.10
but I can't do that by the version of 1.12.2

**Comment by RiskyKen** [comment]
Fixed for next build!

Oh are we going to see a mod spotlight? You were the first person to do a Armourer's Workshop one. :smile:

**Comment by RiskyKen** [comment]
Version 1.1 will be live on curse forge soon. https://minecraft.curseforge.com/projects/dakimakura-mod/files
