### ISSUE TITLE
Causes serious client lag when used by the server

### ISSUE THREAD

**Issue by THHakureiReimu** [RiskyKen/DakimakuraMod#4]
Minecraft : 1.7.10
Forge : 1614
Minecraft Server : Kcauldron 1.7.10
DakimakuraMod 1.1

Server and client only install Andrew's Vanilla Mobs, join the server and enter the dakimakura inventory,client is lag and not responding.

**Comment by RiskyKen** [comment]
Have you tried without Kcauldron do you still get the issue?

Also can you send me a debug crash. (hold C + F3 for 10 seconds)

**Comment by RiskyKen** [comment]
On info given.
